name: Environment
main: com.mcme.environment.Environment
version: ${project.version}
author: Fraspace5
api-version: 1.15
softdepend: [WorldEdit,PluginUtils,ProtocolLib]
website: ${project.url}

commands:
  environment:
    aliases: [env,en]
    description: Region command
permissions:
  environment.admin:
            default: op