name: Environment
main: com.mcme.environment.Environment
version: ${project.version}
author: Fraspace5
api-version: 1.16
softdepend: [WorldEdit,PluginUtils,ProtocolLib]
website: ${project.url}

commands:
  environment:
    aliases: [env,en]
    description: Region command
permissions:
    env.user:
            description: Permission for users
    env.staff:
            default: op
            description: Allows to use all the commands of this plugin[Guide+]
    env.reload:
            description: Allows to reload
 #Copyright (C) 2020 MCME (Fraspace5)