name: Environment
main: com.mcme.me.fraspace5.environment.Environment
version: ${project.version}
author: Fraspace5
softdepend: [WorldGuard]
website: ${project.url}

commands:
  environment:
    aliases: [env]
    description: Region command
permissions:
  environment.admin:
            default: op